version: "3.9"

services:
  server:
    container_name: express-server
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - fullstask-net

  client:
    build: ./client
    container_name: react-client
    networks:
      - fullstask-net
    ports:
      - "8080:80"
    depends_on:
      - server

networks:
  fullstask-net:
    driver: "bridge"
